android {
    signingConfigs {
        dzDebug {
            storeFile file('keystore/dzstream-debug.jks')
            storePassword 'dzstream2026'
            keyAlias 'dzstream'
            keyPassword 'dzstream2026'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.dzDebug
        }
    }
}
